artifacts:
- md5: 620d5c068e4ca408ad99c244f8706fce
  name: jmx_prometheus_javaagent
  target: jmx_prometheus_javaagent-0.3.1.redhat-00006.jar
description: ^ Provides support for configuring Prometheus.  Basic usage is JAVA_OPTS="$JAVA_OPTS
  $(source $JBOSS_CONTAINER_PROMETHEUS_MODULE/prometheus-opts; get_prometheus_opts)"
envs:
- name: JBOSS_CONTAINER_PROMETHEUS_MODULE
  value: /opt/jboss/container/prometheus
- name: AB_PROMETHEUS_JMX_EXPORTER_PORT
  value: 9799
- name: AB_PROMETHEUS_JMX_EXPORTER_CONFIG
  value: /opt/jboss/container/prometheus/etc/jmx-exporter-config.yaml
execute:
- directory: jboss.container.prometheus.bash
  module_name: jboss.container.prometheus.bash
  name: jboss.container.prometheus.bash/configure.sh
  script: configure.sh
labels: []
modules:
  install:
  - name: jboss.container.prometheus.api
  repositories: []
name: jboss.container.prometheus.bash
osbs: {}
packages:
  install: []
  repositories: []
ports: []
schema_version: 1
version: '1.0'
volumes: []
